title: dipak-amazonfavourites
description: My favorite Amazon products and reviews
baseurl: ""
url: "https://dipakhk7750-rgb.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock
